### PR TITLE
Late night math fixes

### PR DESCRIPTION
**Pull request by JakeRoggenbuck**

### CODE REVIEW

**Comment by Camerooooon** [comment]
Truly a 5 o clock moment

**Comment by Shuzhengz** [comment]
U do know that sleep is a thing right lol

**Comment by adamhutchings** [comment]
This is early morning, not late night

**Review by Camerooooon — APPROVED** [review]
Looks good, compiles on arch linux

**Review by Shuzhengz — APPROVED** [review]
Microsoft approves

**Review by Shuzhengz — APPROVED** [review]
Redhat also approves

**Review by Shuzhengz — APPROVED** [review]
Another approval cuz y not

**Pull request merged**
